version: '2'
services:
  ftpd:
    image: fauria/vsftpd
    ports:
     - "21:21"
     - "20:20"
     - "21100-21110:21100-21110"
    volumes:
      - "./data/data:/home/vsftpd"
      - "./data/log:/var/log/vsftpd"
    privileged: true
    environment:
      - "FTP_USER=serkan"
      - "FTP_PASS=1234"

